# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final01.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *


class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(500, 600)
        icon = QIcon()
        icon.addFile(u"sources/img.png", QSize(), QIcon.Normal, QIcon.Off)
        Form.setWindowIcon(icon)
        self.label_20 = QLabel(Form)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(130, 40, 251, 61))
        font = QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setLayoutDirection(Qt.LeftToRight)
        self.label_20.setAutoFillBackground(False)
        self.pushButton = QPushButton(Form)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(190, 100, 101, 41))
        self.tabWidget = QTabWidget(Form)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(90, 180, 321, 381))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.label_5 = QLabel(self.tab)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(90, 40, 131, 51))
        font1 = QFont()
        font1.setPointSize(12)
        self.label_5.setFont(font1)
        self.verticalLayoutWidget = QWidget(self.tab)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(80, 110, 160, 131))
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.label_2 = QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName(u"label_2")

        self.verticalLayout.addWidget(self.label_2)

        self.dateEdit = QDateEdit(self.verticalLayoutWidget)
        self.dateEdit.setObjectName(u"dateEdit")
        self.dateEdit.setMaximumDate(QDate(2022, 5, 13))
        self.dateEdit.setMinimumDate(QDate(2020, 1, 21))

        self.verticalLayout.addWidget(self.dateEdit)

        self.label_3 = QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName(u"label_3")

        self.verticalLayout.addWidget(self.label_3)

        self.dateEdit_2 = QDateEdit(self.verticalLayoutWidget)
        self.dateEdit_2.setObjectName(u"dateEdit_2")
        self.dateEdit_2.setMaximumDate(QDate(2022, 5, 13))
        self.dateEdit_2.setMinimumDate(QDate(2020, 1, 21))

        self.verticalLayout.addWidget(self.dateEdit_2)

        self.horizontalLayoutWidget = QWidget(self.tab)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(40, 260, 241, 80))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.label = QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName(u"label")

        self.horizontalLayout.addWidget(self.label)

        self.comboBox = QComboBox(self.horizontalLayoutWidget)
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setMaxVisibleItems(50)

        self.horizontalLayout.addWidget(self.comboBox)

        self.pushButton_2 = QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName(u"pushButton_2")

        self.horizontalLayout.addWidget(self.pushButton_2)

        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.horizontalLayoutWidget_2 = QWidget(self.tab_2)
        self.horizontalLayoutWidget_2.setObjectName(u"horizontalLayoutWidget_2")
        self.horizontalLayoutWidget_2.setGeometry(QRect(40, 250, 241, 80))
        self.horizontalLayout_2 = QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.label_9 = QLabel(self.horizontalLayoutWidget_2)
        self.label_9.setObjectName(u"label_9")

        self.horizontalLayout_2.addWidget(self.label_9)

        self.comboBox_2 = QComboBox(self.horizontalLayoutWidget_2)
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setMaxVisibleItems(50)

        self.horizontalLayout_2.addWidget(self.comboBox_2)

        self.pushButton_3 = QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_3.setObjectName(u"pushButton_3")

        self.horizontalLayout_2.addWidget(self.pushButton_3)

        self.verticalLayoutWidget_2 = QWidget(self.tab_2)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(80, 120, 161, 111))
        self.verticalLayout_3 = QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.label_7 = QLabel(self.verticalLayoutWidget_2)
        self.label_7.setObjectName(u"label_7")

        self.verticalLayout_3.addWidget(self.label_7)

        self.label_8 = QLabel(self.verticalLayoutWidget_2)
        self.label_8.setObjectName(u"label_8")

        self.verticalLayout_3.addWidget(self.label_8)

        self.spinBox = QSpinBox(self.verticalLayoutWidget_2)
        self.spinBox.setObjectName(u"spinBox")

        self.verticalLayout_3.addWidget(self.spinBox)

        self.label_6 = QLabel(self.tab_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(100, 50, 111, 51))
        self.label_6.setFont(font1)
        self.label_6.setFrameShadow(QFrame.Plain)
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Form)

        self.tabWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"\u57fa\u4e8espark\u7684\u75ab\u60c5\u5206\u6790\u7cfb\u7edf", None))
        self.label_20.setText(QCoreApplication.translate("Form", u"\u57fa\u4e8espark\u7684\u75ab\u60c5\u5206\u6790\u7cfb\u7edf", None))
        self.pushButton.setText(QCoreApplication.translate("Form", u"\u6570\u636e\u83b7\u53d6", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"\u5386\u53f2\u75ab\u60c5\u6570\u636e\u67e5\u770b", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"\u8bf7\u9009\u62e9\u65f6\u95f4", None))
        self.dateEdit.setDisplayFormat(QCoreApplication.translate("Form", u"yyyy-MM-dd", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"\u5230", None))
        self.dateEdit_2.setDisplayFormat(QCoreApplication.translate("Form", u"yyyy-MM-dd", None))
        self.label.setText(QCoreApplication.translate("Form", u"\u8bf7\u9009\u62e9\u5dde", None))
        self.pushButton_2.setText(QCoreApplication.translate("Form", u"\u786e\u8ba4", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("Form", u"\u5386\u53f2\u6570\u636e", None))
        self.label_9.setText(QCoreApplication.translate("Form", u"\u8bf7\u9009\u62e9\u5dde", None))
        self.pushButton_3.setText(QCoreApplication.translate("Form", u"\u786e\u8ba4", None))
        self.label_7.setText(QCoreApplication.translate("Form", u"\u8bf7\u8f93\u5165\u672a\u6765\u60f3\u9884\u6d4b\u7684\u5929\u6570", None))
        self.label_8.setText(QCoreApplication.translate("Form", u"\u81ea2022-05-13\u5f00\u59cb", None))
        self.label_6.setText(QCoreApplication.translate("Form", u"\u75ab\u60c5\u6570\u636e\u9884\u6d4b", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("Form", u"\u672a\u6765\u9884\u6d4b", None))
    # retranslateUi


